services:
  - type: web
    name: flask-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    autoDeploy: true

  - type: worker
    name: discord-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python discord_bot.py"
    autoDeploy: true
