services:
  - type: web
    name: discord-bot-lugus
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python discord_bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        fromDatabase: DISCORD_BOT_TOKEN  # możesz też wpisać bezpośrednio: value: "TwójToken"
